### ISSUE TITLE
可以设置默认不是第一个标签显示吗

### ISSUE THREAD

**Issue by watermelonJun** [wanliyang1990/NavigationBar#1]
我用的 NavitationFollowScrollLayout    我的标签集合是上个页面传过来的    比如传了个 1 2 3  我想问问这个可以设置默认非第一个标签状态吗

**Comment by ywl5320** [comment]
这个好像没有，你可以自己添加一个方法来实现这种功能。

**Comment by watermelonJun** [comment]
你好 请问可以给段实现的代码吗  测试没问题我可以给你红包表谢意  拜托了

**Comment by ywl5320** [comment]
添加了一个设置的方法，你试试：
`@Override
    protected void onResume() {
        super.onResume();
        navitationFollowScrollLayout.setCurrentItem(3);
    }`

**Comment by watermelonJun** [comment]
大佬  给个微信 我给你发红包

**Comment by ywl5320** [comment]
算了 发什么红包哦
